x-environment: &shared-envvar
  POSTGRES_USER: "pairings"
  POSTGRES_PASSWORD: "postgres"
  DATABASE_URL: "postgresql://pairings:postgres@db:5432/postgres"
  ALLOWED_HOSTS: '["edh.marqueewinq.xyz", "localhost"]'
  CORS_ALLOWED_ORIGINS: '["https://edh.marqueewinq.xyz"]'
  BASE_URL: "https://edh.marqueewinq.xyz/"
  DONATE_LINK_RU: "https://www.tinkoff.ru/rm/vinogradov.mark2/aAtTu4590"
  EMAIL_HOST: "mail.smtp2go.com"
  EMAIL_PORT: 2525

services:
  db:
    image: postgres:16
    environment:
      <<: *shared-envvar
    volumes:
      - ./misc/dbdata:/var/lib/postgresql/data

  web:
    image: edhpairings
    build: .
    environment:
      <<: *shared-envvar
    env_file:
      - .env
    command: >
      bash -c "while ! nc -w 1 -z db 5432;
               do sleep 0.1;
               done;
               uv run python manage.py migrate;
               uv run python manage.py collectstatic --noinput;
               uv run gunicorn pairings.wsgi -b 0.0.0.0:8000"
    volumes:
      - ./pairings:/code/pairings
      - ./pyproject.toml:/code/pyproject.toml:ro
      - ./uv.lock:/code/uv.lock:ro
      - static_files:/code/pairings/static
    working_dir: /code/pairings
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    ports:
      - "8010:80"
    volumes:
      - ./misc/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_files:/static:ro
    depends_on:
      - web

  test:
    image: edhpairings
    build: .
    environment:
      <<: *shared-envvar
    env_file:
      - .env
    command: >
      bash -c "while ! nc -w 1 -z db 5432;
               do sleep 0.1;
               done;
               uv run python manage.py migrate;
               uv run python manage.py test;
               "
    volumes:
      - ./pairings:/code/pairings
      - ./pyproject.toml:/code/pyproject.toml:ro
      - ./uv.lock:/code/uv.lock:ro
    working_dir: /code/pairings
    depends_on:
      - db

volumes:
  static_files:
