# Generated by Django 2.2.28 on 2023-01-16 13:24

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsentry",
            name="html_entry_ru",
            field=tinymce.models.HTMLField(default=""),
        ),
    ]
